<?php

namespace Database\Seeders;

use App\Models\Ingredient;
use App\Models\Recipe;
use Illuminate\Database\Seeder;

class GlobalRecipeSeeder extends Seeder
{
    public function run(): void
    {
        $recipes = [
            [
                'title' => 'Pancakes classiques',
                'type' => 'petit-déjeuner',
                'description' => 'Des pancakes moelleux parfaits pour le petit-déjeuner.',
                'instructions' => "Étape 1 : Mélanger la farine, le sucre et la levure.\nÉtape 2 : Ajouter les œufs puis le lait progressivement.\nÉtape 3 : Faire fondre le beurre et l’incorporer à la pâte.\nÉtape 4 : Cuire de petites louches de pâte dans une poêle chaude jusqu’à coloration des deux côtés.",
                'base_servings' => 1,
                'ingredients' => [
                    ['name' => 'Farine', 'quantity' => 150, 'unit' => 'g', 'category' => 'épicerie sucrée'],
                    ['name' => 'Sucre', 'quantity' => 20, 'unit' => 'g', 'category' => 'épicerie sucrée'],
                    ['name' => 'Levure chimique', 'quantity' => 1, 'unit' => 'c. à café', 'category' => 'épicerie sucrée'],
                    ['name' => 'Œufs', 'quantity' => 2, 'unit' => '', 'category' => 'crèmerie'],
                    ['name' => 'Lait', 'quantity' => 20, 'unit' => 'cl', 'category' => 'crèmerie'],
                    ['name' => 'Beurre', 'quantity' => 20, 'unit' => 'g', 'category' => 'crèmerie'],
                ],
            ],
            [
                'title' => 'Porridge banane cannelle',
                'type' => 'petit-déjeuner',
                'description' => 'Un porridge réconfortant et rapide à préparer.',
                'instructions' => "Étape 1 : Verser les flocons d’avoine et le lait dans une casserole.\nÉtape 2 : Faire chauffer doucement en remuant jusqu’à épaississement.\nÉtape 3 : Ajouter la banane écrasée et la cannelle.\nÉtape 4 : Servir chaud.",
                'base_servings' => 1,
                'ingredients' => [
                    ['name' => 'Flocons d’avoine', 'quantity' => 50, 'unit' => 'g', 'category' => 'épicerie sucrée'],
                    ['name' => 'Lait', 'quantity' => 20, 'unit' => 'cl', 'category' => 'crèmerie'],
                    ['name' => 'Banane', 'quantity' => 1, 'unit' => '', 'category' => 'fruits et légumes'],
                    ['name' => 'Cannelle', 'quantity' => 1, 'unit' => 'pincée', 'category' => 'épicerie sucrée'],
                ],
            ],
            [
                'title' => 'Omelette aux fines herbes',
                'type' => 'petit-déjeuner',
                'description' => 'Une omelette simple et savoureuse.',
                'instructions' => "Étape 1 : Battre les œufs avec du sel et du poivre.\nÉtape 2 : Ajouter les fines herbes ciselées.\nÉtape 3 : Cuire dans une poêle avec un peu de beurre.\nÉtape 4 : Replier l’omelette et servir aussitôt.",
                'base_servings' => 1,
                'ingredients' => [
                    ['name' => 'Œufs', 'quantity' => 3, 'unit' => '', 'category' => 'crèmerie'],
                    ['name' => 'Beurre', 'quantity' => 10, 'unit' => 'g', 'category' => 'crèmerie'],
                    ['name' => 'Persil', 'quantity' => 0.25, 'unit' => 'botte', 'category' => 'fruits et légumes'],
                    ['name' => 'Ciboulette', 'quantity' => 0.25, 'unit' => 'botte', 'category' => 'fruits et légumes'],
                ],
            ],
            [
                'title' => 'Bruschetta tomates basilic',
                'type' => 'entrée',
                'description' => 'Une entrée fraîche et parfumée aux saveurs italiennes.',
                'instructions' => "Étape 1 : Couper les tomates en petits dés.\nÉtape 2 : Mélanger avec l’ail haché, le basilic et l’huile d’olive.\nÉtape 3 : Griller les tranches de pain.\nÉtape 4 : Répartir les tomates assaisonnées sur le pain et servir.",
                'base_servings' => 1,
                'ingredients' => [
                    ['name' => 'Tomates', 'quantity' => 3, 'unit' => '', 'category' => 'fruits et légumes'],
                    ['name' => 'Basilic', 'quantity' => 0.5, 'unit' => 'botte', 'category' => 'fruits et légumes'],
                    ['name' => 'Ail', 'quantity' => 1, 'unit' => 'gousse', 'category' => 'fruits et légumes'],
                    ['name' => 'Pain', 'quantity' => 4, 'unit' => 'tranche', 'category' => 'épicerie salée'],
                    ['name' => 'Huile d’olive', 'quantity' => 2, 'unit' => 'c. à soupe', 'category' => 'épicerie salée'],
                ],
            ],
            [
                'title' => 'Soupe de légumes',
                'type' => 'entrée',
                'description' => 'Une soupe familiale douce et réconfortante.',
                'instructions' => "Étape 1 : Éplucher et couper les légumes en morceaux.\nÉtape 2 : Faire revenir l’oignon avec un filet d’huile.\nÉtape 3 : Ajouter les légumes et couvrir d’eau.\nÉtape 4 : Laisser cuire jusqu’à ce que les légumes soient tendres.\nÉtape 5 : Mixer puis assaisonner.",
                'base_servings' => 1,
                'ingredients' => [
                    ['name' => 'Carottes', 'quantity' => 3, 'unit' => '', 'category' => 'fruits et légumes'],
                    ['name' => 'Pommes de terre', 'quantity' => 3, 'unit' => '', 'category' => 'fruits et légumes'],
                    ['name' => 'Poireau', 'quantity' => 1, 'unit' => '', 'category' => 'fruits et légumes'],
                    ['name' => 'Oignon', 'quantity' => 1, 'unit' => '', 'category' => 'fruits et légumes'],
                    ['name' => 'Huile d’olive', 'quantity' => 1, 'unit' => 'c. à soupe', 'category' => 'épicerie salée'],
                ],
            ],
            [
                'title' => 'Salade grecque',
                'type' => 'entrée',
                'description' => 'Une salade fraîche à base de légumes croquants et de feta.',
                'instructions' => "Étape 1 : Couper les tomates, le concombre et l’oignon.\nÉtape 2 : Ajouter les olives et la feta émiettée.\nÉtape 3 : Assaisonner avec l’huile d’olive et servir bien frais.",
                'base_servings' => 1,
                'ingredients' => [
                    ['name' => 'Tomates', 'quantity' => 2, 'unit' => '', 'category' => 'fruits et légumes'],
                    ['name' => 'Concombre', 'quantity' => 1, 'unit' => '', 'category' => 'fruits et légumes'],
                    ['name' => 'Oignon rouge', 'quantity' => 0.5, 'unit' => '', 'category' => 'fruits et légumes'],
                    ['name' => 'Feta', 'quantity' => 100, 'unit' => 'g', 'category' => 'crèmerie'],
                    ['name' => 'Olives noires', 'quantity' => 50, 'unit' => 'g', 'category' => 'épicerie salée'],
                    ['name' => 'Huile d’olive', 'quantity' => 2, 'unit' => 'c. à soupe', 'category' => 'épicerie salée'],
                ],
            ],
            [
                'title' => 'Quiche lorraine',
                'type' => 'plat principal',
                'description' => 'Une quiche généreuse et croustillante.',
                'instructions' => "Étape 1 : Étaler la pâte dans un moule.\nÉtape 2 : Faire revenir les lardons.\nÉtape 3 : Mélanger les œufs et la crème.\nÉtape 4 : Répartir les lardons sur la pâte, verser l’appareil puis cuire au four jusqu’à belle coloration.",
                'base_servings' => 1,
                'ingredients' => [
                    ['name' => 'Pâte brisée', 'quantity' => 1, 'unit' => '', 'category' => 'épicerie salée'],
                    ['name' => 'Lardons', 'quantity' => 150, 'unit' => 'g', 'category' => 'boucherie'],
                    ['name' => 'Œufs', 'quantity' => 3, 'unit' => '', 'category' => 'crèmerie'],
                    ['name' => 'Crème', 'quantity' => 20, 'unit' => 'cl', 'category' => 'crèmerie'],
                ],
            ],
            [
                'title' => 'Spaghetti bolognaise',
                'type' => 'plat principal',
                'description' => 'Un classique simple et convivial.',
                'instructions' => "Étape 1 : Faire revenir l’oignon dans un peu d’huile.\nÉtape 2 : Ajouter la viande hachée et cuire quelques minutes.\nÉtape 3 : Incorporer les tomates concassées et laisser mijoter.\nÉtape 4 : Cuire les spaghetti puis servir avec la sauce.",
                'base_servings' => 1,
                'ingredients' => [
                    ['name' => 'Spaghetti', 'quantity' => 200, 'unit' => 'g', 'category' => 'épicerie salée'],
                    ['name' => 'Bœuf haché', 'quantity' => 250, 'unit' => 'g', 'category' => 'boucherie'],
                    ['name' => 'Tomates concassées', 'quantity' => 400, 'unit' => 'g', 'category' => 'épicerie salée'],
                    ['name' => 'Oignon', 'quantity' => 1, 'unit' => '', 'category' => 'fruits et légumes'],
                    ['name' => 'Huile d’olive', 'quantity' => 1, 'unit' => 'c. à soupe', 'category' => 'épicerie salée'],
                ],
            ],
            [
                'title' => 'Lasagnes bolognaise',
                'type' => 'plat principal',
                'description' => 'Des lasagnes fondantes à partager.',
                'instructions' => "Étape 1 : Préparer une sauce bolognaise avec l’oignon, le bœuf haché et les tomates.\nÉtape 2 : Préparer une béchamel simple.\nÉtape 3 : Alterner les couches de pâtes, de sauce bolognaise et de béchamel.\nÉtape 4 : Ajouter le fromage râpé et cuire au four.",
                'base_servings' => 1,
                'ingredients' => [
                    ['name' => 'Feuilles de lasagnes', 'quantity' => 9, 'unit' => '', 'category' => 'épicerie salée'],
                    ['name' => 'Bœuf haché', 'quantity' => 300, 'unit' => 'g', 'category' => 'boucherie'],
                    ['name' => 'Tomates concassées', 'quantity' => 400, 'unit' => 'g', 'category' => 'épicerie salée'],
                    ['name' => 'Oignon', 'quantity' => 1, 'unit' => '', 'category' => 'fruits et légumes'],
                    ['name' => 'Lait', 'quantity' => 40, 'unit' => 'cl', 'category' => 'crèmerie'],
                    ['name' => 'Beurre', 'quantity' => 30, 'unit' => 'g', 'category' => 'crèmerie'],
                    ['name' => 'Farine', 'quantity' => 30, 'unit' => 'g', 'category' => 'épicerie sucrée'],
                    ['name' => 'Fromage râpé', 'quantity' => 80, 'unit' => 'g', 'category' => 'crèmerie'],
                ],
            ],
            [
                'title' => 'Risotto aux champignons',
                'type' => 'plat principal',
                'description' => 'Un risotto crémeux et parfumé.',
                'instructions' => "Étape 1 : Faire revenir l’oignon dans un peu de beurre.\nÉtape 2 : Ajouter le riz et le nacrer.\nÉtape 3 : Incorporer le bouillon chaud progressivement en remuant.\nÉtape 4 : Ajouter les champignons poêlés.\nÉtape 5 : Terminer avec du parmesan.",
                'base_servings' => 1,
                'ingredients' => [
                    ['name' => 'Riz arborio', 'quantity' => 180, 'unit' => 'g', 'category' => 'épicerie salée'],
                    ['name' => 'Champignons de Paris', 'quantity' => 200, 'unit' => 'g', 'category' => 'fruits et légumes'],
                    ['name' => 'Oignon', 'quantity' => 1, 'unit' => '', 'category' => 'fruits et légumes'],
                    ['name' => 'Beurre', 'quantity' => 20, 'unit' => 'g', 'category' => 'crèmerie'],
                    ['name' => 'Parmesan', 'quantity' => 40, 'unit' => 'g', 'category' => 'crèmerie'],
                ],
            ],
            [
                'title' => 'Curry de légumes',
                'type' => 'plat principal',
                'description' => 'Un plat parfumé, simple et coloré.',
                'instructions' => "Étape 1 : Couper les légumes en morceaux.\nÉtape 2 : Faire revenir l’oignon puis ajouter la pâte de curry.\nÉtape 3 : Ajouter les légumes et le lait de coco.\nÉtape 4 : Laisser mijoter jusqu’à ce que les légumes soient tendres.\nÉtape 5 : Servir avec du riz.",
                'base_servings' => 1,
                'ingredients' => [
                    ['name' => 'Carottes', 'quantity' => 2, 'unit' => '', 'category' => 'fruits et légumes'],
                    ['name' => 'Courgette', 'quantity' => 1, 'unit' => '', 'category' => 'fruits et légumes'],
                    ['name' => 'Pois chiches', 'quantity' => 250, 'unit' => 'g', 'category' => 'épicerie salée'],
                    ['name' => 'Lait de coco', 'quantity' => 20, 'unit' => 'cl', 'category' => 'épicerie salée'],
                    ['name' => 'Oignon', 'quantity' => 1, 'unit' => '', 'category' => 'fruits et légumes'],
                    ['name' => 'Pâte de curry', 'quantity' => 1, 'unit' => 'c. à soupe', 'category' => 'épicerie salée'],
                    ['name' => 'Riz', 'quantity' => 180, 'unit' => 'g', 'category' => 'épicerie salée'],
                ],
            ],
            [
                'title' => 'Dahl de lentilles corail',
                'type' => 'plat principal',
                'description' => 'Un plat végétarien doux et nourrissant.',
                'instructions' => "Étape 1 : Faire revenir l’oignon avec les épices.\nÉtape 2 : Ajouter les lentilles corail et les tomates.\nÉtape 3 : Verser de l’eau et laisser cuire doucement.\nÉtape 4 : Ajouter le lait de coco en fin de cuisson puis servir.",
                'base_servings' => 1,
                'ingredients' => [
                    ['name' => 'Lentilles corail', 'quantity' => 200, 'unit' => 'g', 'category' => 'épicerie salée'],
                    ['name' => 'Tomates concassées', 'quantity' => 200, 'unit' => 'g', 'category' => 'épicerie salée'],
                    ['name' => 'Lait de coco', 'quantity' => 20, 'unit' => 'cl', 'category' => 'épicerie salée'],
                    ['name' => 'Oignon', 'quantity' => 1, 'unit' => '', 'category' => 'fruits et légumes'],
                    ['name' => 'Curry', 'quantity' => 1, 'unit' => 'c. à café', 'category' => 'épicerie salée'],
                ],
            ],
            [
                'title' => 'Chili con carne',
                'type' => 'plat principal',
                'description' => 'Un plat mijoté épicé et généreux.',
                'instructions' => "Étape 1 : Faire revenir l’oignon.\nÉtape 2 : Ajouter la viande hachée puis cuire quelques minutes.\nÉtape 3 : Incorporer les haricots rouges, les tomates et les épices.\nÉtape 4 : Laisser mijoter avant de servir.",
                'base_servings' => 1,
                'ingredients' => [
                    ['name' => 'Bœuf haché', 'quantity' => 300, 'unit' => 'g', 'category' => 'boucherie'],
                    ['name' => 'Haricots rouges', 'quantity' => 250, 'unit' => 'g', 'category' => 'épicerie salée'],
                    ['name' => 'Tomates concassées', 'quantity' => 400, 'unit' => 'g', 'category' => 'épicerie salée'],
                    ['name' => 'Oignon', 'quantity' => 1, 'unit' => '', 'category' => 'fruits et légumes'],
                    ['name' => 'Cumin', 'quantity' => 1, 'unit' => 'c. à café', 'category' => 'épicerie salée'],
                ],
            ],
            [
                'title' => 'Ratatouille',
                'type' => 'plat principal',
                'description' => 'Un plat de légumes du soleil mijotés.',
                'instructions' => "Étape 1 : Couper tous les légumes en morceaux.\nÉtape 2 : Faire revenir l’oignon puis ajouter les autres légumes.\nÉtape 3 : Laisser mijoter à feu doux jusqu’à ce que les légumes soient fondants.\nÉtape 4 : Assaisonner et servir.",
                'base_servings' => 1,
                'ingredients' => [
                    ['name' => 'Courgette', 'quantity' => 2, 'unit' => '', 'category' => 'fruits et légumes'],
                    ['name' => 'Aubergine', 'quantity' => 1, 'unit' => '', 'category' => 'fruits et légumes'],
                    ['name' => 'Tomates', 'quantity' => 4, 'unit' => '', 'category' => 'fruits et légumes'],
                    ['name' => 'Poivron', 'quantity' => 1, 'unit' => '', 'category' => 'fruits et légumes'],
                    ['name' => 'Oignon', 'quantity' => 1, 'unit' => '', 'category' => 'fruits et légumes'],
                    ['name' => 'Huile d’olive', 'quantity' => 2, 'unit' => 'c. à soupe', 'category' => 'épicerie salée'],
                ],
            ],
            [
                'title' => 'Poulet rôti aux herbes',
                'type' => 'plat principal',
                'description' => 'Un poulet tendre et doré au four.',
                'instructions' => "Étape 1 : Déposer le poulet dans un plat.\nÉtape 2 : Ajouter l’ail, les herbes et un filet d’huile.\nÉtape 3 : Entourer de pommes de terre.\nÉtape 4 : Cuire au four en arrosant régulièrement.",
                'base_servings' => 1,
                'ingredients' => [
                    ['name' => 'Poulet entier', 'quantity' => 1, 'unit' => '', 'category' => 'boucherie'],
                    ['name' => 'Pommes de terre', 'quantity' => 800, 'unit' => 'g', 'category' => 'fruits et légumes'],
                    ['name' => 'Ail', 'quantity' => 3, 'unit' => 'gousse', 'category' => 'fruits et légumes'],
                    ['name' => 'Thym', 'quantity' => 2, 'unit' => 'branche', 'category' => 'fruits et légumes'],
                    ['name' => 'Huile d’olive', 'quantity' => 2, 'unit' => 'c. à soupe', 'category' => 'épicerie salée'],
                ],
            ],
            [
                'title' => 'Saumon au four citron aneth',
                'type' => 'plat principal',
                'description' => 'Un plat léger et parfumé, très simple à préparer.',
                'instructions' => "Étape 1 : Déposer les pavés de saumon dans un plat.\nÉtape 2 : Arroser de jus de citron.\nÉtape 3 : Ajouter l’aneth et un filet d’huile.\nÉtape 4 : Cuire au four jusqu’à ce que le saumon soit fondant.",
                'base_servings' => 1,
                'ingredients' => [
                    ['name' => 'Saumon', 'quantity' => 2, 'unit' => 'pavé', 'category' => 'poissonnerie'],
                    ['name' => 'Citron', 'quantity' => 1, 'unit' => '', 'category' => 'fruits et légumes'],
                    ['name' => 'Aneth', 'quantity' => 0.5, 'unit' => 'botte', 'category' => 'fruits et légumes'],
                    ['name' => 'Huile d’olive', 'quantity' => 1, 'unit' => 'c. à soupe', 'category' => 'épicerie salée'],
                ],
            ],
            [
                'title' => 'Wok de légumes',
                'type' => 'plat principal',
                'description' => 'Un plat rapide et croquant.',
                'instructions' => "Étape 1 : Couper les légumes en fines lamelles.\nÉtape 2 : Faire chauffer un filet d’huile dans un wok.\nÉtape 3 : Saisir les légumes à feu vif.\nÉtape 4 : Ajouter la sauce soja et servir aussitôt.",
                'base_servings' => 1,
                'ingredients' => [
                    ['name' => 'Carottes', 'quantity' => 2, 'unit' => '', 'category' => 'fruits et légumes'],
                    ['name' => 'Poivron', 'quantity' => 1, 'unit' => '', 'category' => 'fruits et légumes'],
                    ['name' => 'Courgette', 'quantity' => 1, 'unit' => '', 'category' => 'fruits et légumes'],
                    ['name' => 'Sauce soja', 'quantity' => 2, 'unit' => 'c. à soupe', 'category' => 'épicerie salée'],
                    ['name' => 'Huile', 'quantity' => 1, 'unit' => 'c. à soupe', 'category' => 'épicerie salée'],
                ],
            ],
            [
                'title' => 'Brownie au chocolat',
                'type' => 'dessert',
                'description' => 'Un brownie fondant au chocolat.',
                'instructions' => "Étape 1 : Faire fondre le chocolat avec le beurre.\nÉtape 2 : Fouetter les œufs avec le sucre.\nÉtape 3 : Ajouter le mélange chocolaté puis la farine.\nÉtape 4 : Verser dans un moule et cuire au four.",
                'base_servings' => 1,
                'ingredients' => [
                    ['name' => 'Chocolat noir', 'quantity' => 200, 'unit' => 'g', 'category' => 'épicerie sucrée'],
                    ['name' => 'Beurre', 'quantity' => 120, 'unit' => 'g', 'category' => 'crèmerie'],
                    ['name' => 'Sucre', 'quantity' => 120, 'unit' => 'g', 'category' => 'épicerie sucrée'],
                    ['name' => 'Œufs', 'quantity' => 3, 'unit' => '', 'category' => 'crèmerie'],
                    ['name' => 'Farine', 'quantity' => 80, 'unit' => 'g', 'category' => 'épicerie sucrée'],
                ],
            ],
            [
                'title' => 'Cookies aux pépites de chocolat',
                'type' => 'dessert',
                'description' => 'Des cookies croustillants à l’extérieur et moelleux à cœur.',
                'instructions' => "Étape 1 : Mélanger le beurre mou avec le sucre.\nÉtape 2 : Ajouter l’œuf puis la farine.\nÉtape 3 : Incorporer les pépites de chocolat.\nÉtape 4 : Former des boules et cuire au four.",
                'base_servings' => 1,
                'ingredients' => [
                    ['name' => 'Farine', 'quantity' => 200, 'unit' => 'g', 'category' => 'épicerie sucrée'],
                    ['name' => 'Sucre', 'quantity' => 100, 'unit' => 'g', 'category' => 'épicerie sucrée'],
                    ['name' => 'Beurre', 'quantity' => 100, 'unit' => 'g', 'category' => 'crèmerie'],
                    ['name' => 'Œufs', 'quantity' => 1, 'unit' => '', 'category' => 'crèmerie'],
                    ['name' => 'Pépites de chocolat', 'quantity' => 120, 'unit' => 'g', 'category' => 'épicerie sucrée'],
                ],
            ],
            [
                'title' => 'Banana bread',
                'type' => 'dessert',
                'description' => 'Un gâteau moelleux à la banane, idéal pour le goûter.',
                'instructions' => "Étape 1 : Écraser les bananes.\nÉtape 2 : Mélanger avec les œufs et le sucre.\nÉtape 3 : Ajouter la farine et le beurre fondu.\nÉtape 4 : Verser dans un moule et cuire au four.",
                'base_servings' => 1,
                'ingredients' => [
                    ['name' => 'Banane', 'quantity' => 3, 'unit' => '', 'category' => 'fruits et légumes'],
                    ['name' => 'Farine', 'quantity' => 200, 'unit' => 'g', 'category' => 'épicerie sucrée'],
                    ['name' => 'Sucre', 'quantity' => 100, 'unit' => 'g', 'category' => 'épicerie sucrée'],
                    ['name' => 'Œufs', 'quantity' => 2, 'unit' => '', 'category' => 'crèmerie'],
                    ['name' => 'Beurre', 'quantity' => 80, 'unit' => 'g', 'category' => 'crèmerie'],
                    ['name' => 'Levure chimique', 'quantity' => 1, 'unit' => 'c. à café', 'category' => 'épicerie sucrée'],
                ],
            ],
            [
                'title' => 'Smoothie banane fruits rouges',
                'type' => 'boisson',
                'description' => 'Une boisson fruitée et fraîche.',
                'instructions' => "Étape 1 : Verser tous les ingrédients dans un blender.\nÉtape 2 : Mixer jusqu’à obtenir une texture lisse.\nÉtape 3 : Servir bien frais.",
                'base_servings' => 1,
                'ingredients' => [
                    ['name' => 'Banane', 'quantity' => 1, 'unit' => '', 'category' => 'fruits et légumes'],
                    ['name' => 'Fruits rouges surgelés', 'quantity' => 150, 'unit' => 'g', 'category' => 'surgelés'],
                    ['name' => 'Yaourt nature', 'quantity' => 1, 'unit' => 'pot', 'category' => 'crèmerie'],
                    ['name' => 'Lait', 'quantity' => 15, 'unit' => 'cl', 'category' => 'crèmerie'],
                ],
            ],
            [
                'title' => 'Crêpes classiques',
                'type' => 'petit-déjeuner',
                'description' => 'Des crêpes fines et moelleuses faciles à préparer.',
                'instructions' => "Étape 1 : Mélanger la farine, les œufs et le sucre.\nÉtape 2 : Ajouter le lait progressivement pour éviter les grumeaux.\nÉtape 3 : Laisser reposer la pâte quelques minutes.\nÉtape 4 : Cuire les crêpes dans une poêle chaude légèrement beurrée.",
                'base_servings' => 1,
                'ingredients' => [
                    ['name' => 'Farine', 'quantity' => 125, 'unit' => 'g', 'category' => 'épicerie sucrée'],
                    ['name' => 'Œufs', 'quantity' => 2, 'unit' => '', 'category' => 'crèmerie'],
                    ['name' => 'Lait', 'quantity' => 25, 'unit' => 'cl', 'category' => 'crèmerie'],
                    ['name' => 'Sucre', 'quantity' => 15, 'unit' => 'g', 'category' => 'épicerie sucrée'],
                    ['name' => 'Beurre', 'quantity' => 20, 'unit' => 'g', 'category' => 'crèmerie'],
                ],
            ],
            [
                'title' => 'Granola maison',
                'type' => 'petit-déjeuner',
                'description' => 'Un granola croustillant à savourer avec du yaourt ou du lait.',
                'instructions' => "Étape 1 : Mélanger les flocons d’avoine, le miel et les amandes concassées.\nÉtape 2 : Ajouter un filet d’huile puis bien mélanger.\nÉtape 3 : Étaler sur une plaque.\nÉtape 4 : Cuire au four jusqu’à ce que le granola soit doré.",
                'base_servings' => 1,
                'ingredients' => [
                    ['name' => 'Flocons d’avoine', 'quantity' => 80, 'unit' => 'g', 'category' => 'épicerie sucrée'],
                    ['name' => 'Miel', 'quantity' => 20, 'unit' => 'g', 'category' => 'épicerie sucrée'],
                    ['name' => 'Amandes', 'quantity' => 30, 'unit' => 'g', 'category' => 'épicerie sucrée'],
                    ['name' => 'Huile', 'quantity' => 1, 'unit' => 'c. à soupe', 'category' => 'épicerie salée'],
                ],
            ],
            [
                'title' => 'Houmous classique',
                'type' => 'entrée',
                'description' => 'Une crème de pois chiches onctueuse à partager.',
                'instructions' => "Étape 1 : Égoutter les pois chiches.\nÉtape 2 : Mixer avec l’ail, le jus de citron et l’huile d’olive.\nÉtape 3 : Ajuster la texture avec un peu d’eau si besoin.\nÉtape 4 : Servir frais.",
                'base_servings' => 1,
                'ingredients' => [
                    ['name' => 'Pois chiches', 'quantity' => 200, 'unit' => 'g', 'category' => 'épicerie salée'],
                    ['name' => 'Ail', 'quantity' => 1, 'unit' => 'gousse', 'category' => 'fruits et légumes'],
                    ['name' => 'Citron', 'quantity' => 0.5, 'unit' => '', 'category' => 'fruits et légumes'],
                    ['name' => 'Huile d’olive', 'quantity' => 2, 'unit' => 'c. à soupe', 'category' => 'épicerie salée'],
                ],
            ],
            [
                'title' => 'Guacamole maison',
                'type' => 'entrée',
                'description' => 'Une préparation fraîche et crémeuse à base d’avocat.',
                'instructions' => "Étape 1 : Écraser les avocats à la fourchette.\nÉtape 2 : Ajouter le jus de citron, l’oignon rouge émincé et la tomate coupée en dés.\nÉtape 3 : Mélanger et assaisonner.\nÉtape 4 : Servir bien frais.",
                'base_servings' => 1,
                'ingredients' => [
                    ['name' => 'Avocat', 'quantity' => 2, 'unit' => '', 'category' => 'fruits et légumes'],
                    ['name' => 'Citron', 'quantity' => 0.5, 'unit' => '', 'category' => 'fruits et légumes'],
                    ['name' => 'Oignon rouge', 'quantity' => 0.25, 'unit' => '', 'category' => 'fruits et légumes'],
                    ['name' => 'Tomates', 'quantity' => 1, 'unit' => '', 'category' => 'fruits et légumes'],
                ],
            ],
            [
                'title' => 'Velouté de courgettes',
                'type' => 'entrée',
                'description' => 'Un velouté léger et doux, parfait pour toutes les saisons.',
                'instructions' => "Étape 1 : Couper les courgettes et la pomme de terre en morceaux.\nÉtape 2 : Faire revenir l’oignon avec un filet d’huile.\nÉtape 3 : Ajouter les légumes et couvrir d’eau.\nÉtape 4 : Cuire puis mixer avec la crème.",
                'base_servings' => 1,
                'ingredients' => [
                    ['name' => 'Courgette', 'quantity' => 2, 'unit' => '', 'category' => 'fruits et légumes'],
                    ['name' => 'Pommes de terre', 'quantity' => 1, 'unit' => '', 'category' => 'fruits et légumes'],
                    ['name' => 'Oignon', 'quantity' => 0.5, 'unit' => '', 'category' => 'fruits et légumes'],
                    ['name' => 'Crème', 'quantity' => 5, 'unit' => 'cl', 'category' => 'crèmerie'],
                ],
            ],
            [
                'title' => 'Taboulé libanais',
                'type' => 'entrée',
                'description' => 'Une salade fraîche aux herbes et au boulgour.',
                'instructions' => "Étape 1 : Cuire ou réhydrater le boulgour selon les indications.\nÉtape 2 : Couper les tomates et le concombre en petits dés.\nÉtape 3 : Ciseler le persil et la menthe.\nÉtape 4 : Mélanger tous les ingrédients avec le jus de citron et l’huile d’olive.",
                'base_servings' => 1,
                'ingredients' => [
                    ['name' => 'Boulgour', 'quantity' => 80, 'unit' => 'g', 'category' => 'épicerie salée'],
                    ['name' => 'Tomates', 'quantity' => 2, 'unit' => '', 'category' => 'fruits et légumes'],
                    ['name' => 'Concombre', 'quantity' => 0.5, 'unit' => '', 'category' => 'fruits et légumes'],
                    ['name' => 'Persil', 'quantity' => 0.5, 'unit' => 'botte', 'category' => 'fruits et légumes'],
                    ['name' => 'Menthe', 'quantity' => 0.25, 'unit' => 'botte', 'category' => 'fruits et légumes'],
                    ['name' => 'Citron', 'quantity' => 1, 'unit' => '', 'category' => 'fruits et légumes'],
                    ['name' => 'Huile d’olive', 'quantity' => 2, 'unit' => 'c. à soupe', 'category' => 'épicerie salée'],
                ],
            ],
            [
                'title' => 'Quiche légumes chèvre',
                'type' => 'plat principal',
                'description' => 'Une quiche fondante aux légumes et au chèvre.',
                'instructions' => "Étape 1 : Étaler la pâte dans un moule.\nÉtape 2 : Faire revenir les courgettes et l’oignon.\nÉtape 3 : Mélanger les œufs et la crème.\nÉtape 4 : Répartir les légumes et le chèvre sur la pâte, verser l’appareil puis cuire au four.",
                'base_servings' => 1,
                'ingredients' => [
                    ['name' => 'Pâte brisée', 'quantity' => 1, 'unit' => '', 'category' => 'épicerie salée'],
                    ['name' => 'Courgette', 'quantity' => 1, 'unit' => '', 'category' => 'fruits et légumes'],
                    ['name' => 'Oignon', 'quantity' => 0.5, 'unit' => '', 'category' => 'fruits et légumes'],
                    ['name' => 'Chèvre', 'quantity' => 80, 'unit' => 'g', 'category' => 'crèmerie'],
                    ['name' => 'Œufs', 'quantity' => 2, 'unit' => '', 'category' => 'crèmerie'],
                    ['name' => 'Crème', 'quantity' => 10, 'unit' => 'cl', 'category' => 'crèmerie'],
                ],
            ],
            [
                'title' => 'Spaghetti sauce tomate basilic',
                'type' => 'plat principal',
                'description' => 'Des pâtes simples et parfumées à la tomate.',
                'instructions' => "Étape 1 : Cuire les spaghetti.\nÉtape 2 : Faire revenir l’ail dans l’huile d’olive.\nÉtape 3 : Ajouter les tomates concassées et laisser mijoter.\nÉtape 4 : Ajouter le basilic puis servir avec les pâtes.",
                'base_servings' => 1,
                'ingredients' => [
                    ['name' => 'Spaghetti', 'quantity' => 100, 'unit' => 'g', 'category' => 'épicerie salée'],
                    ['name' => 'Tomates concassées', 'quantity' => 200, 'unit' => 'g', 'category' => 'épicerie salée'],
                    ['name' => 'Ail', 'quantity' => 1, 'unit' => 'gousse', 'category' => 'fruits et légumes'],
                    ['name' => 'Basilic', 'quantity' => 0.25, 'unit' => 'botte', 'category' => 'fruits et légumes'],
                    ['name' => 'Huile d’olive', 'quantity' => 1, 'unit' => 'c. à soupe', 'category' => 'épicerie salée'],
                ],
            ],
            [
                'title' => 'Pâtes carbonara',
                'type' => 'plat principal',
                'description' => 'Un plat de pâtes crémeux et très rapide à réaliser.',
                'instructions' => "Étape 1 : Cuire les pâtes.\nÉtape 2 : Faire revenir les lardons.\nÉtape 3 : Mélanger les œufs et le fromage râpé.\nÉtape 4 : Ajouter les pâtes chaudes aux lardons puis incorporer le mélange hors du feu.",
                'base_servings' => 1,
                'ingredients' => [
                    ['name' => 'Pâtes', 'quantity' => 100, 'unit' => 'g', 'category' => 'épicerie salée'],
                    ['name' => 'Lardons', 'quantity' => 100, 'unit' => 'g', 'category' => 'boucherie'],
                    ['name' => 'Œufs', 'quantity' => 1, 'unit' => '', 'category' => 'crèmerie'],
                    ['name' => 'Parmesan', 'quantity' => 30, 'unit' => 'g', 'category' => 'crèmerie'],
                ],
            ],
            [
                'title' => 'Gnocchis sauce tomate',
                'type' => 'plat principal',
                'description' => 'Des gnocchis moelleux avec une sauce tomate maison.',
                'instructions' => "Étape 1 : Cuire les gnocchis selon les indications.\nÉtape 2 : Faire revenir l’ail dans l’huile.\nÉtape 3 : Ajouter les tomates concassées et laisser mijoter.\nÉtape 4 : Mélanger les gnocchis à la sauce et servir.",
                'base_servings' => 1,
                'ingredients' => [
                    ['name' => 'Gnocchis', 'quantity' => 250, 'unit' => 'g', 'category' => 'épicerie salée'],
                    ['name' => 'Tomates concassées', 'quantity' => 200, 'unit' => 'g', 'category' => 'épicerie salée'],
                    ['name' => 'Ail', 'quantity' => 1, 'unit' => 'gousse', 'category' => 'fruits et légumes'],
                    ['name' => 'Huile d’olive', 'quantity' => 1, 'unit' => 'c. à soupe', 'category' => 'épicerie salée'],
                ],
            ],
            [
                'title' => 'Pizza margherita',
                'type' => 'plat principal',
                'description' => 'Une pizza classique à la tomate et à la mozzarella.',
                'instructions' => "Étape 1 : Étaler la pâte à pizza.\nÉtape 2 : Répartir la sauce tomate.\nÉtape 3 : Ajouter la mozzarella et un filet d’huile d’olive.\nÉtape 4 : Cuire au four puis ajouter le basilic avant de servir.",
                'base_servings' => 1,
                'ingredients' => [
                    ['name' => 'Pâte à pizza', 'quantity' => 1, 'unit' => '', 'category' => 'épicerie salée'],
                    ['name' => 'Sauce tomate', 'quantity' => 100, 'unit' => 'g', 'category' => 'épicerie salée'],
                    ['name' => 'Mozzarella', 'quantity' => 125, 'unit' => 'g', 'category' => 'crèmerie'],
                    ['name' => 'Basilic', 'quantity' => 0.25, 'unit' => 'botte', 'category' => 'fruits et légumes'],
                    ['name' => 'Huile d’olive', 'quantity' => 1, 'unit' => 'c. à soupe', 'category' => 'épicerie salée'],
                ],
            ],
            [
                'title' => 'Pizza végétarienne',
                'type' => 'plat principal',
                'description' => 'Une pizza garnie de légumes colorés.',
                'instructions' => "Étape 1 : Étaler la pâte à pizza.\nÉtape 2 : Ajouter la sauce tomate.\nÉtape 3 : Répartir les légumes et la mozzarella.\nÉtape 4 : Cuire au four jusqu’à ce que la pâte soit dorée.",
                'base_servings' => 1,
                'ingredients' => [
                    ['name' => 'Pâte à pizza', 'quantity' => 1, 'unit' => '', 'category' => 'épicerie salée'],
                    ['name' => 'Sauce tomate', 'quantity' => 100, 'unit' => 'g', 'category' => 'épicerie salée'],
                    ['name' => 'Mozzarella', 'quantity' => 100, 'unit' => 'g', 'category' => 'crèmerie'],
                    ['name' => 'Poivron', 'quantity' => 0.5, 'unit' => '', 'category' => 'fruits et légumes'],
                    ['name' => 'Champignons de Paris', 'quantity' => 80, 'unit' => 'g', 'category' => 'fruits et légumes'],
                    ['name' => 'Courgette', 'quantity' => 0.5, 'unit' => '', 'category' => 'fruits et légumes'],
                ],
            ],
            [
                'title' => 'Chili sin carne',
                'type' => 'plat principal',
                'description' => 'Une version végétarienne du chili, généreuse et parfumée.',
                'instructions' => "Étape 1 : Faire revenir l’oignon.\nÉtape 2 : Ajouter les haricots rouges, les tomates et les épices.\nÉtape 3 : Laisser mijoter à feu doux.\nÉtape 4 : Servir bien chaud.",
                'base_servings' => 1,
                'ingredients' => [
                    ['name' => 'Haricots rouges', 'quantity' => 250, 'unit' => 'g', 'category' => 'épicerie salée'],
                    ['name' => 'Tomates concassées', 'quantity' => 200, 'unit' => 'g', 'category' => 'épicerie salée'],
                    ['name' => 'Oignon', 'quantity' => 0.5, 'unit' => '', 'category' => 'fruits et légumes'],
                    ['name' => 'Cumin', 'quantity' => 1, 'unit' => 'c. à café', 'category' => 'épicerie salée'],
                ],
            ],
            [
                'title' => 'Gratin dauphinois',
                'type' => 'plat principal',
                'description' => 'Un classique fondant à base de pommes de terre et de crème.',
                'instructions' => "Étape 1 : Éplucher et couper les pommes de terre en fines rondelles.\nÉtape 2 : Frotter le plat avec l’ail.\nÉtape 3 : Disposer les pommes de terre puis verser la crème.\nÉtape 4 : Cuire au four jusqu’à ce que le gratin soit bien doré.",
                'base_servings' => 1,
                'ingredients' => [
                    ['name' => 'Pommes de terre', 'quantity' => 300, 'unit' => 'g', 'category' => 'fruits et légumes'],
                    ['name' => 'Crème', 'quantity' => 15, 'unit' => 'cl', 'category' => 'crèmerie'],
                    ['name' => 'Ail', 'quantity' => 1, 'unit' => 'gousse', 'category' => 'fruits et légumes'],
                ],
            ],
            [
                'title' => 'Hachis parmentier',
                'type' => 'plat principal',
                'description' => 'Un plat familial composé de purée et de viande hachée.',
                'instructions' => "Étape 1 : Préparer une purée avec les pommes de terre.\nÉtape 2 : Faire revenir l’oignon et la viande hachée.\nÉtape 3 : Déposer la viande dans un plat puis recouvrir de purée.\nÉtape 4 : Cuire au four pour faire gratiner.",
                'base_servings' => 1,
                'ingredients' => [
                    ['name' => 'Pommes de terre', 'quantity' => 300, 'unit' => 'g', 'category' => 'fruits et légumes'],
                    ['name' => 'Bœuf haché', 'quantity' => 150, 'unit' => 'g', 'category' => 'boucherie'],
                    ['name' => 'Oignon', 'quantity' => 0.5, 'unit' => '', 'category' => 'fruits et légumes'],
                    ['name' => 'Lait', 'quantity' => 5, 'unit' => 'cl', 'category' => 'crèmerie'],
                    ['name' => 'Beurre', 'quantity' => 15, 'unit' => 'g', 'category' => 'crèmerie'],
                ],
            ],
            [
                'title' => 'Poulet citron ail',
                'type' => 'plat principal',
                'description' => 'Un plat de poulet simple, parfumé et rapide.',
                'instructions' => "Étape 1 : Faire revenir le poulet dans une poêle avec un filet d’huile.\nÉtape 2 : Ajouter l’ail haché.\nÉtape 3 : Arroser de jus de citron.\nÉtape 4 : Laisser cuire doucement puis servir.",
                'base_servings' => 1,
                'ingredients' => [
                    ['name' => 'Poulet', 'quantity' => 180, 'unit' => 'g', 'category' => 'boucherie'],
                    ['name' => 'Citron', 'quantity' => 1, 'unit' => '', 'category' => 'fruits et légumes'],
                    ['name' => 'Ail', 'quantity' => 1, 'unit' => 'gousse', 'category' => 'fruits et légumes'],
                    ['name' => 'Huile d’olive', 'quantity' => 1, 'unit' => 'c. à soupe', 'category' => 'épicerie salée'],
                ],
            ],
            [
                'title' => 'Poisson en papillote',
                'type' => 'plat principal',
                'description' => 'Un poisson tendre cuit au four avec des légumes.',
                'instructions' => "Étape 1 : Déposer le poisson sur une feuille de cuisson.\nÉtape 2 : Ajouter les légumes émincés et un filet d’huile.\nÉtape 3 : Refermer la papillote.\nÉtape 4 : Cuire au four puis servir immédiatement.",
                'base_servings' => 1,
                'ingredients' => [
                    ['name' => 'Poisson blanc', 'quantity' => 180, 'unit' => 'g', 'category' => 'poissonnerie'],
                    ['name' => 'Courgette', 'quantity' => 0.5, 'unit' => '', 'category' => 'fruits et légumes'],
                    ['name' => 'Carottes', 'quantity' => 1, 'unit' => '', 'category' => 'fruits et légumes'],
                    ['name' => 'Citron', 'quantity' => 0.5, 'unit' => '', 'category' => 'fruits et légumes'],
                    ['name' => 'Huile d’olive', 'quantity' => 1, 'unit' => 'c. à soupe', 'category' => 'épicerie salée'],
                ],
            ],
            [
                'title' => 'Tofu sauté aux légumes',
                'type' => 'plat principal',
                'description' => 'Un plat végétarien rapide et équilibré.',
                'instructions' => "Étape 1 : Couper le tofu en dés.\nÉtape 2 : Faire revenir les légumes dans une poêle.\nÉtape 3 : Ajouter le tofu et la sauce soja.\nÉtape 4 : Cuire à feu vif quelques minutes puis servir.",
                'base_servings' => 1,
                'ingredients' => [
                    ['name' => 'Tofu', 'quantity' => 150, 'unit' => 'g', 'category' => 'autre'],
                    ['name' => 'Carottes', 'quantity' => 1, 'unit' => '', 'category' => 'fruits et légumes'],
                    ['name' => 'Courgette', 'quantity' => 0.5, 'unit' => '', 'category' => 'fruits et légumes'],
                    ['name' => 'Poivron', 'quantity' => 0.5, 'unit' => '', 'category' => 'fruits et légumes'],
                    ['name' => 'Sauce soja', 'quantity' => 2, 'unit' => 'c. à soupe', 'category' => 'épicerie salée'],
                ],
            ],
            [
                'title' => 'Buddha bowl au quinoa',
                'type' => 'plat principal',
                'description' => 'Un bol complet avec quinoa, légumes et pois chiches.',
                'instructions' => "Étape 1 : Cuire le quinoa.\nÉtape 2 : Préparer les légumes et les pois chiches.\nÉtape 3 : Répartir tous les éléments dans un bol.\nÉtape 4 : Ajouter un filet d’huile d’olive avant de servir.",
                'base_servings' => 1,
                'ingredients' => [
                    ['name' => 'Quinoa', 'quantity' => 80, 'unit' => 'g', 'category' => 'épicerie salée'],
                    ['name' => 'Pois chiches', 'quantity' => 120, 'unit' => 'g', 'category' => 'épicerie salée'],
                    ['name' => 'Avocat', 'quantity' => 0.5, 'unit' => '', 'category' => 'fruits et légumes'],
                    ['name' => 'Carottes', 'quantity' => 1, 'unit' => '', 'category' => 'fruits et légumes'],
                    ['name' => 'Concombre', 'quantity' => 0.5, 'unit' => '', 'category' => 'fruits et légumes'],
                    ['name' => 'Huile d’olive', 'quantity' => 1, 'unit' => 'c. à soupe', 'category' => 'épicerie salée'],
                ],
            ],
            [
                'title' => 'Gâteau au chocolat moelleux',
                'type' => 'dessert',
                'description' => 'Un gâteau au chocolat simple et très fondant.',
                'instructions' => "Étape 1 : Faire fondre le chocolat avec le beurre.\nÉtape 2 : Mélanger les œufs et le sucre.\nÉtape 3 : Ajouter la farine puis le chocolat fondu.\nÉtape 4 : Verser dans un moule et cuire au four.",
                'base_servings' => 1,
                'ingredients' => [
                    ['name' => 'Chocolat noir', 'quantity' => 120, 'unit' => 'g', 'category' => 'épicerie sucrée'],
                    ['name' => 'Beurre', 'quantity' => 80, 'unit' => 'g', 'category' => 'crèmerie'],
                    ['name' => 'Sucre', 'quantity' => 80, 'unit' => 'g', 'category' => 'épicerie sucrée'],
                    ['name' => 'Œufs', 'quantity' => 2, 'unit' => '', 'category' => 'crèmerie'],
                    ['name' => 'Farine', 'quantity' => 60, 'unit' => 'g', 'category' => 'épicerie sucrée'],
                ],
            ],
            [
                'title' => 'Crumble aux pommes',
                'type' => 'dessert',
                'description' => 'Un dessert croustillant et fruité.',
                'instructions' => "Étape 1 : Éplucher et couper les pommes.\nÉtape 2 : Les disposer dans un plat.\nÉtape 3 : Mélanger la farine, le sucre et le beurre du bout des doigts.\nÉtape 4 : Répartir la pâte à crumble sur les pommes puis cuire au four.",
                'base_servings' => 1,
                'ingredients' => [
                    ['name' => 'Pommes', 'quantity' => 3, 'unit' => '', 'category' => 'fruits et légumes'],
                    ['name' => 'Farine', 'quantity' => 80, 'unit' => 'g', 'category' => 'épicerie sucrée'],
                    ['name' => 'Sucre', 'quantity' => 60, 'unit' => 'g', 'category' => 'épicerie sucrée'],
                    ['name' => 'Beurre', 'quantity' => 60, 'unit' => 'g', 'category' => 'crèmerie'],
                ],
            ],
            [
                'title' => 'Tiramisu classique',
                'type' => 'dessert',
                'description' => 'Un dessert italien crémeux au café.',
                'instructions' => "Étape 1 : Séparer les blancs des jaunes d’œufs.\nÉtape 2 : Mélanger les jaunes avec le sucre puis ajouter le mascarpone.\nÉtape 3 : Monter les blancs en neige et les incorporer délicatement.\nÉtape 4 : Tremper les biscuits dans le café, monter le tiramisu en couches puis réserver au frais.",
                'base_servings' => 1,
                'ingredients' => [
                    ['name' => 'Mascarpone', 'quantity' => 125, 'unit' => 'g', 'category' => 'crèmerie'],
                    ['name' => 'Œufs', 'quantity' => 2, 'unit' => '', 'category' => 'crèmerie'],
                    ['name' => 'Sucre', 'quantity' => 40, 'unit' => 'g', 'category' => 'épicerie sucrée'],
                    ['name' => 'Biscuits à la cuillère', 'quantity' => 8, 'unit' => '', 'category' => 'épicerie sucrée'],
                    ['name' => 'Café', 'quantity' => 10, 'unit' => 'cl', 'category' => 'boissons'],
                ],
            ],
        ];

        foreach ($recipes as $data) {
            $recipe = Recipe::query()->create([
                'household_id' => null,
                'is_global' => true,
                'title' => $data['title'],
                'type' => $data['type'],
                'description' => $data['description'],
                'instructions' => $data['instructions'],
                'is_ai_generated' => false,
                'base_servings' => (int) $data['base_servings'],
            ]);

            $syncData = [];

            foreach ($data['ingredients'] as $ingredientData) {
                $ingredient = Ingredient::query()->firstOrCreate(
                    ['name' => mb_strtolower(trim($ingredientData['name']))],
                    ['category' => $ingredientData['category'] ?? 'autre']
                );

                $syncData[$ingredient->id] = [
                    'quantity' => (float) $ingredientData['quantity'],
                    'unit' => (string) ($ingredientData['unit'] ?? ''),
                ];
            }

            $recipe->ingredients()->sync($syncData);
        }
    }
}